<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishAot>true</PublishAot>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AssemblyName>FileManage.Launcher</AssemblyName>
    <RootNamespace>FileManage.Launcher</RootNamespace>
    <!-- 与主应用一致的应用图标（根目录 FileManage.exe 显示用） -->
    <ApplicationIcon>..\FileManage.App\app.ico</ApplicationIcon>
    <OptimizationPreference>Speed</OptimizationPreference>
    <StripSymbols>true</StripSymbols>
  </PropertyGroup>

</Project>
